import {Urbanist} from "next/font/google"
import "./globals.css";
import Footer from "@/components/navigation/footer";
import Navbar from "@/components/navigation/navbar";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100","200", "300", "400", "500", "600", "800", "900"],
  variable: "--font-urbanist"
})


export const metadata = {
  title: "Univel Realtors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
